# Linguagem Utilizada para Desenvolver a Aplicação
language: python

# Versão que a aplicação suporta.
python:
  - "3.8"

# Instalação de Módulos que são necessários para a Aplicação.
install:
  - pip install -r requirements_test.txt

# Versão do Ubuntu
dist: focal
sudo: enabled

# Ativando o MySQL
services:
  - mysql

env:
  global:
   - CLOUD_SQL_DATABASE_NAME="playlist"
   - CLOUD_SQL_PASSWORD="123456"
   - CLOUD_SQL_USERNAME="playuser"
   - DB_LOCAL_HOST="127.0.0.1"

before_install:
  - sudo mysql -e "CREATE USER 'playuser'@'%' IDENTIFIED BY '123456';"
  - sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'playuser'@'%' WITH GRANT OPTION;"
  - sudo mysql -u playuser -p < setup/Playlist.sql
    
# Defini o script de Teste que deve rodar toda vez que o código for alterado.
script:
  - python -m unittest -v test
