# Linguagem Utilizada para Desenvolver a Aplicação
language: python

# Versão que a aplicação suporta.
python:
  - "3.8"

# Instalação de Módulos que são necessários para a Aplicação.
install:
  - pip install -r requirements_test.txt

# Versão do Ubuntu
dist: focal

# Ativando o MySQL
services:
  - mysql

env:
  global:
   - PYTHONWARNINGS="ignore::DeprecationWarning"
   - CLOUD_SQL_DATABASE_NAME="playlist"
   - CLOUD_SQL_USERNAME="playuser"
   - DB_LOCAL_HOST="127.0.0.1"

before_install:
  - openssl aes-256-cbc -K $encrypted_5b6cb3bb221c_key -iv $encrypted_5b6cb3bb221c_iv
    -in setup/gcpkey.json.enc -out ../gcpkey.json -d
  - bash ./setup/mysql_travis.sh

# Defini o script de Teste que deve rodar toda vez que o código for alterado.
script:
  - python -m unittest -v test

#before_deploy: "bash ./setup/gae.sh"

# Definir o Deploy no Heroku
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  edge: true 
  app: playlist-2
  on:
      branch: main

# - provider: gae
#   keyfile: "../gcpkey.json"
#   project: playlistpy-code
#   skip_cleanup: true
#   on:
#     branch: main

