runtime: python37

# IMPORTANTE NUNCA ENVIE SUAS CREDENCIAIS PARA O GITHUB.
# ARQUIVO EXEMPLO PARA DEPLOY DO GCP APPENGINE
env_variables:
  CLOUD_SQL_USERNAME: usuario
  CLOUD_SQL_PASSWORD: senha
  CLOUD_SQL_DATABASE_NAME: banco
  CLOUD_SQL_CONNECTION_NAME: conexao_sqlcloud
