# Use root/example as user/password credentials
version: '3.1'

services:

  backend:
    build: ./app
    ports:
      - "5000:8080"
    environment:
        PORT: 8080
        CLOUD_SQL_USERNAME: playuser
        CLOUD_SQL_PASSWORD: 123456
        CLOUD_SQL_DATABASE_NAME: playlist
        DB_LOCAL_HOST: db

  frontend:
    build: ./frontend
    environment:
       BACKEND_URL: "http://backend:8080"
    ports:
      - "3000:8080"

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
